apiVersion: v1
kind: Secret
metadata:
  name: ai-tls
  namespace: ai-ns
type: kubernetes.io/tls
# The TLS secret must contain keys named 'tls.crt' and 'tls.key' that contain the certificate and private key to use for TLS.
data:
  tls.crt: <base64_tls_cert>
  tls.key: <base64_tls_key>